name: twitter_delete
description: You can delete Twitter tweets. You can also delete  past tweets by tweet.js too.
version: 1.0.0
homepage: https://blog.logicky.com
author: edo1z <endo.yuta@logicky.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dotenv: ^1.0.0
  intl: ^0.16.0
  twitter_1user: ^1.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
